### ISSUE TITLE
Clicking "go" over colony opens that colony

### ISSUE THREAD

**Issue by Beep6581** [FreeCol/freecol#10]
74e2fd2cf

I click a unit, hit "g" on the keyboard, then click a colony as the destination. The unit should just go there and nothing more, but Freecol also opens that colony window.

**Comment by HighwayofLife** [comment]
This is annoying, I have noticed it as well.

**Comment by Mattia83** [comment]
Actually the bug seems more general. Anywhere you try to use the "g" button, it just highlights the selected tile, but the unit doesn't go there. 
If on the selected tile there is something that can open a menu (e.g. a colony or a native village), that menu opens up, but the unit does not move.

**Comment by Beep6581** [comment]
Still an issue in latest master.

Do the developers ever read these issues?
@Nikerabbit @ Mike Pope

**Comment by Beep6581** [comment]
@Nikerabbit https://github.com/FreeCol/freecol/commits/master most non-localisation commits are by Mike Pope - I wanted to ping him, but there is no @MikePope entity, so I ping you, the next-most-active entity. Please don't accuse me of pinging you at random as if I had nothing better to do.

FreeCol has a SourceForge project, and there is this GitHub project. I looked through all of these GitHub issues and I don't see any clear dev interaction. Could you clarify what the situation regarding FreeCol GitHub issues is? Do FreeCol devs check them or are we wasting our time reporting things here?

**Comment by TropicalBastos** [comment]
This issue has been fixed in PR #51
