### ISSUE TITLE
Cannot open map files on MacOs

### ISSUE THREAD

**Issue by mfasold** [FreeCol/freecol#104]
Since this is my first issue, I would like to thank you for the great work on this project!

In my setting, it is not possible to open existing map files. In the "Open" dialog of the map editor, the "Files of Type" text box shows "filter.fsm" (it probably should show "*.fsm"). Since it cannot be changed, it is impossible to select one of the map files that exist in this folder (see image). Note that it is also not possible to paste a text in the "File Name" box.

FreeCol Version: git-20220217 (on MacOS with Java 17)

<img width="599" alt="image" src="https://user-images.githubusercontent.com/726676/157900133-ba48310c-259a-486a-9ea3-8a712b1fa8d8.png">

**Comment by mpope042** [comment]
The "filter.fsm" part has mislead you.  That is just a translation key, for which there is no translation (which is a different bug).  When fixed it will just contain descriptive text, like "FreeCol Saved Maps (*.fsm)".  It should be possible to open existing maps, however I suspect there are none present in your default user maps directory --- the navigation controls at the top should allow you to change directory to somewhere that does have .fsm files, and/or you should be able to create some in the current directory, which should then be loadable.

**Comment by mfasold** [comment]
I was indeed confused by the "filter.fsm" part and by the "maps" folder name. I somehow expected it to be the "maps" folder in the installation folder, while the dialog opens in the user maps folder. Thank you for the clarification!
