### ISSUE TITLE
Scout cannot visit native villages directly from a ship if tribe unknown

### ISSUE THREAD

**Issue by mfasold** [FreeCol/freecol#105]
My scout is trying to talk to the chief of Indian villages, directly from a ship. This worked fine for the first village I was visiting (the tribe was already known to me). But when I tried the same with the next village, there was an error after clicking on "Ask to speak to chief", namely "The server cannot do that". In the second case, the tribe was not yet known to me. I can provide a savegame, if that might be helpful.

[FreeCol.log](https://github.com/FreeCol/freecol/files/8246032/FreeCol.log)

**Comment by mpope042** [comment]
> IIRC in original Colonization you needed to visit villages with scout from land.

Correct.  FreeCol supports both behaviours depending on an option.  It should *not* however ever say "The server can not do that" at the user level, so there is a bug here either way.

Please report bugs to the [sourceforge bug tracker](https://sourceforge.net/p/freecol/bugs/) which explains good things to put in a bug report, of which a saved game would indeed be helpful in this case.  There was alas nothing helpful in the log file this time.  The github freecol presence is intended only as a mirror.
