### ISSUE TITLE
Moving too many goods cancels the transfer instead of transfering the possible amount

### ISSUE THREAD

**Issue by sumpfralle** [FreeCol/freecol#109]
How to reproduce:
* wagon is filled with 100 horses and 90 units of ore
* warehouse contains 20 units of ore
* drag ore from warehouse to wagon (with the mouse)

Now I expected the ore slot in the wagon to be filled (up to 100 units).
Instead the transfer was cancelled (no change).

Using "shift-drag" suggests the proper amount of ore to be transferred (10). But it would be much nicer to simply transfer whatever is possible with a simple drag operation.

(I think, that behavior existed somewhen, but I am not completely sure)

Thank you!

**Comment by mpope042** [comment]
Please use the sourceforge [Improvement Requests](https://sourceforge.net/p/freecol/improvement-requests/) tracker for this sort of issue.  We are using github as a backup mirror, and this issues tracker gets little attention.

**Comment by sumpfralle** [comment]
Ah, thank you!
I was already wondering about the low number of issues file here :)

How about disabling the issue tracker here in order to redirect people to the sourceforge issue tracker? Or maybe place an explanatory text in the issue template, which makes it obvious, where issues should go to?

I moved the issue to https://sourceforge.net/p/freecol/improvement-requests/241/.
