### ISSUE TITLE
Some turn report messages are printed twice

### ISSUE THREAD

**Issue by Beep6581** [FreeCol/freecol#11]
74e2fd2cf

Some messages in the end of turn report are shown twice.
![imgur-2017_11_18-15 54 40](https://user-images.githubusercontent.com/5844619/32981665-d2c21676-cc78-11e7-8f1e-2f356257751b.png)
https://filebin.net/uyutckx3pxzx0pyr

**Comment by mpope042** [comment]
Not reproducible in trunk.
