### ISSUE TITLE
flashing ocean

### ISSUE THREAD

**Issue by CharlieAtlas** [FreeCol/freecol#111]
just upgraded to 0.12.0
I previously had the nightly build from what appears to be February 17

I upgraded to test whether the issue from #107 was fixed or not.  First thing i noticed when starting up is that the water flashes.  Sometimes it is a section of ocean, some times it is the whole ocean.  I cant quite see a pattern to it.  
The main ocean flashes lighter about every 2.5 seconds.  the timing seems fairly constant for that.  
The shore flashes quite a bit darker periodically.  sometimes it is the whole shore, other times it is just sections of it.  

Are there any settings that might help?

**Comment by Calebrw** [comment]
Can you share your system settings? Please also attach a save game file where this occurs, a screenshot of the issue (if possible to capture), and most importantly the FreeCol.log file.

**Comment by CharlieAtlas** [comment]
Is there a way to attach those files?  Or just something like google drive links?

**Comment by mpope042** [comment]
You are better off raising issues over on the sourceforge [bug tracker](https://sourceforge.net/p/freecol/bugs). Currently github is our backup mirror.  That said, both places allow you to attach files, and links are fine for large files.

You problem though... do we have animated oceans now?

**Comment by stiangre** [comment]
This issue sounds like you have installed the new version of FreeCol in the same directory as a previous version ... without deleting the old files. These old files are then displayed as part of the animation sequence.

Please try reinstalling to a different directory

If this does not help, then this might apply:
https://sourceforge.net/p/freecol/bugs/3254/

**Comment by CharlieAtlas** [comment]
That did it, thanks!
