### ISSUE TITLE
Can it still be stable?

### ISSUE THREAD

**Issue by rainbowdesign** [FreeCol/freecol#113]
Hello,
The last two times i tried the game - nightlys and it was very unstable.
The first time was about 2 years ago and i was not able to land my units from ship and some other glitches.
Last week i tried it again and it completely crashed when reaching land (so 2 minutes after starting).

The last stable version is from 2015 and i really would like new features and a polished game so i like to play the new version.
But from that experience i wonder if the game is now too riddled with bugs to get a stable version in a reasonable time. Do you see it the same way?

**Comment by wintertime** [comment]
Hi,

2 times in 2 years is not a statistically relevant sample. IMHO you were just unlucky and could have tried a slightly older nightly. Additionally, if you notice a bug and do not report it noone will know and therefore noone could fix it.

A new stable release just came out for you to try. Your assumption about why it took that long is just wrong. This is a volunteer project and there was a long stretch of a lack of volunteer time, which looks like it improved recently.

**Comment by rainbowdesign** [comment]
I found the new version. But it does crash soon after starting for me and it does not seem to give any kind of log.

**Comment by mpope042** [comment]
"it crashes" is not a useful bug report.  Obviously it does not do that for us.  If you tell us pretty much nothing we are left guessing what your problem is.  However if forced to guess, I would suspect your Java is not sufficiently up to date.  So how about you tell us what Java version you have installed?

**Comment by rainbowdesign** [comment]
To make sure java is up to date i tried to run the update tool thats included in java. It did run and uninstall my old versions but then it did not install a new version. i had java 8 and java 10 since i installed 10 for freecol nighly (www.java.com was down then). Now i have no java since www.java.com is still down and it does not strike me as a good idea to just take a random version from a search engine since the java versioning is confusing.

**Comment by stiangre** [comment]
Are you running Windows? If yes, try the installer that includes Java:
https://sourceforge.net/projects/freecol/files/freecol/freecol-0.12.0/freecol-0.12.0-with-java.exe/download

**Comment by stiangre** [comment]
Closing since you have not provided a response to the previous question. I'm guessing the Windows installer worked for you :-)

**Comment by rainbowdesign** [comment]
Thankyou, yes, i got it working :)
