### ISSUE TITLE
Game hangs: WARNING: Illegal move for: unit:6567 type: MOVE_NO_ACCESS_LAND

### ISSUE THREAD

**Issue by ingmar** [FreeCol/freecol#118]
I think the relevant log messages are these:

`net.sf.freecol.client.gui.panel.InfoPanel update
	INFO: InfoPanel updated UNIT -> UNIT with unit [unit:6567 dutch merchantman 4/5]
	Fri Aug 19 14:52:12 CEST 2022
	Thread: 30
net.sf.freecol.common.model.Player clientError
	WARNING: Illegal move for: unit:6567 type: MOVE_NO_ACCESS_LAND from: tile:2996 to: tile:2995
	Fri Aug 19 14:52:12 CEST 2022
	Thread: 205916
net.sf.freecol.common.model.Player clientError
	WARNING: Illegal move for: unit:6567 type: MOVE_NO_ACCESS_LAND from: tile:2996 to: tile:2995
	Fri Aug 19 14:52:12 CEST 2022
	Thread: 205917
net.sf.freecol.common.model.Player clientError
	WARNING: Illegal move for: unit:6567 type: MOVE_NO_ACCESS_LAND from: tile:2996 to: tile:2995
	Fri Aug 19 14:52:12 CEST 2022
	Thread: 205918
net.sf.freecol.client.gui.panel.InfoPanel update
	INFO: InfoPanel updated UNIT -> UNIT with unit [unit:6567 dutch merchantman 4/5]
	Fri Aug 19 14:52:12 CEST 2022
	Thread: 30
net.sf.freecol.common.model.Player clientError
	WARNING: Illegal move for: unit:6567 type: MOVE_NO_ACCESS_LAND from: tile:2996 to: tile:3035
	Fri Aug 19 14:52:12 CEST 2022
	Thread: 205919
net.sf.freecol.common.model.Player clientError
	WARNING: Illegal move for: unit:6567 type: MOVE_NO_ACCESS_LAND from: tile:2996 to: tile:2995
	Fri Aug 19 14:52:12 CEST 2022
	Thread: 205920
net.sf.freecol.common.model.Player clientError
	WARNING: Illegal move for: unit:6567 type: MOVE_NO_ACCESS_LAND from: tile:2996 to: tile:2995
	Fri Aug 19 14:52:12 CEST 2022
	Thread: 205921
net.sf.freecol.common.model.Player clientError
	WARNING: Illegal move for: unit:6567 type: MOVE_NO_ACCESS_LAND from: tile:2996 to: tile:2995
	Fri Aug 19 14:52:12 CEST 2022
	Thread: 205922
net.sf.freecol.common.model.Player clientError
	WARNING: Illegal move for: unit:6567 type: MOVE_NO_ACCESS_LAND from: tile:2996 to: tile:3035
	Fri Aug 19 14:52:12 CEST 2022
	Thread: 205923
`

This then repeats endlessly, filling up the logfile fast (the thread numbers seem to be constantly increasing). The game shows the error dialog with the link to the logfile and then freezes.

Last Autosave attached: [Autosave-last-turn.zip](https://github.com/FreeCol/freecol/files/9382329/Autosave-last-turn.zip)

**Comment by stiangre** [comment]
A couple of bugs causing this problem were fixed yesterday. Please try our [development build](https://github.com/FreeCol/freecol/releases/tag/latest) and check if the issue has been resolved for you.

**Comment by ingmar** [comment]
Seems fixed in https://github.com/FreeCol/freecol/commit/4aed94381f5b015ca024658c72a4a649ff0f09fc - nice work, and fast! 👍

**Comment by stiangre** [comment]
Great, thanks for reporting :-)
