### ISSUE TITLE
Clicking on tile without units shouldn't change to terrain selection mode

### ISSUE THREAD

**Issue by Szunti** [FreeCol/freecol#15]
I don't know how others play, but I rarely want to select the terrain. Then right click is fine. 

In 0.11.6 I couldn't select terrain with left clicking in unit selection mode and that was perfect for me.
Probably I shouldn't ever click on a tile, but I just do it, mainly because it's the easiest way to scroll the map a couple tiles. Then I always have to change the mode back. It's annoying.

**Comment by Beep6581** [comment]
In addition, in the current master branch d4c258852, when I first click on terrain and then want to select a unit, clicking on the unit does not select it.

**Comment by Beep6581** [comment]
Correction, it seems left-clicking on a unit does select it, but there is no visual cue, and the last-selected terrain tile still has the green frame which indicates that its supposed to be selected.

**Comment by LongboatAline** [comment]
I can confirm this with the nightlies
* Nightly Release: 2018-04-25
* Nightly Release: 2018-04-07 
* Nightly Release: 2018-03-22
It does make the game rather cumbersome to play.

**Comment by wintertime** [comment]
The recent change improved this slightly. Explored tiles can not be selected anymore; I can still select unexplored tiles, though.
Also, switching the view mode still does nothing and the unit is still not blinking.

**Comment by mpope042** [comment]
Selecting a tile now needs a double click.

How are you switching the view mode?  I never do it explicitly.

**Comment by wintertime** [comment]
View menu - Toggle View Mode or Ctrl+Shift+V

In Units View Mode you could:
- click unit - selects it and starts blinking green cursor on it, info on lower right switches to infos about that unit
- click tile - only map movement
- W - move to next unit
- cursor keys - move unit

In other mode (think it was called Map or Tile View Mode):
- clicking a unit or tile - select the tile underneath it and put green cursor without blinking, lower right info shows info about the tile
- if the click was only a few rows/columns from the window edge move the view to center it
- W - nothing
- cursor keys - move green cursor to next tile with centering when needed
- Enter - may open the dialogpanel with tile infos (don't remember this exactly)

**Comment by mpope042** [comment]
OK, I had completely forgotten that existed, no wonder it evaded testing.  I think I have kicked the cursor-blinking/selection code enough in git.a7cdd36.  What remains broken is the InfoPanel.  AFAICT tiles are not displaying at all, and switching between units is as dodgy as ever.

**Comment by mpope042** [comment]
I have split out the sub-info-panels, and AFAICT the mode switching is working OK.  Switching between units with no moves left does weird things, but units with moves are now reliable.  Tile display is just completely broken.  No idea why.  InfoPanel has been a pain for too long.

**Comment by mpope042** [comment]
This is only getting weirder.  AFAICT everything is working fine with my standard test game, but the tile display is always blank if I use the saved game on BR#3173.  Weirder still, if I simplify the Tile display down to just display the image, it is still blank.  Any chance you can have a look wintertime?  I am baffled.

**Comment by mpope042** [comment]
...and just as mysteriously, the problem has gone away.  We have a placeholder bug BR#2806 for this problem on the main bug tracker, so I will close this issue.
