### ISSUE TITLE
Ugly text rendering

### ISSUE THREAD

**Issue by Beep6581** [FreeCol/freecol#21]
Hello

The text rendered in all panels is ugly:
![imgur-2018_04_25-17 00 19](https://user-images.githubusercontent.com/5844619/39254424-5c9b3c8a-48aa-11e8-80a6-6d25a82888fc.png)

The text rendered in tooltips is nice (see the `model.option.useXRender` tooltip):
![imgur-2018_04_25-17 00 42](https://user-images.githubusercontent.com/5844619/39254437-61a42bd8-48aa-11e8-83d1-96e18affb9dd.png)

Can I do anything to make the text render nicely?

nightly-2018-04-07-4-g d4c258852
```text
$ java -version
openjdk version "1.8.0_161"
OpenJDK Runtime Environment (IcedTea 3.7.0) (Gentoo icedtea-3.7.0)
OpenJDK 64-Bit Server VM (build 25.161-b12, mixed mode)
```

**Comment by HighwayofLife** [comment]
Seems like an anti-alias setting is disabled or turned off.

**Comment by Beep6581** [comment]
Adding this to the command line solved it:
`-Dawt.useSystemAAFontSettings=on`

More options: https://wiki.archlinux.org/index.php/Java_Runtime_Environment_fonts#Basic_settings

My full launcher command-line:
```bash
java -Xmx2G -Dsun.java2d.opengl=true -jar "$HOME/programs/code-freecol/FreeCol.jar" --freecol-data "$HOME/programs/code-freecol/data"
```

![imgur-2018_04_29-09 54 13](https://user-images.githubusercontent.com/5844619/39404429-58d22c4e-4b93-11e8-928c-d90be9f8cac1.png)

![imgur-2018_04_29-09 54 28](https://user-images.githubusercontent.com/5844619/39404430-58f7c12a-4b93-11e8-99c3-daca37d66126.png)

I will leave the closing of the issue to you.

**Comment by Beep6581** [comment]
Now I add a `freecol` alias to `~/.bashrc` as follows:
```text
alias freecol='java -Xmx1G -Dsun.java2d.opengl=true -Dawt.useSystemAAFontSettings=on -jar "$HOME/programs/code-freecol/FreeCol.jar" --freecol-data "$HOME/programs/code-freecol/data"'
```
When I want to run freecol, I just type "freecol" without having to `cd` anywhere.

**Comment by mpope042** [comment]
Yep, Java/OS/whatever defaults change and make FreeCol look ugly.  Not a lot we can do about it, but thanks Beep6581 for finding the work around.
