### ISSUE TITLE
GoTo Not Working

### ISSUE THREAD

**Issue by cawoodm** [FreeCol/freecol#23]
When you press G you get "Boot" mouse trails however left clicking on a square does not result in the unit going there. Also, left clicking on a village just brings up the village. RIcht-clicking also does nothing. It's as if the click ignores the fact that we're in GoTo mode.

Right-clicking on a square and saying "Go to this tile" works.

![image](https://user-images.githubusercontent.com/498834/42377832-48c5708c-8125-11e8-97d5-c16bb02ec871.png)

git-s0180425

**Comment by Calebrw** [comment]
This is not a solution, but a workaround. The 'H' key should work and you can select the Colony you wish.

I don't know if the issue you have described affects other Settlements (ie Foreign Colonies and Native Villages).

**Comment by HighwayofLife** [comment]
Fixed in #51
