### ISSUE TITLE
Population growth ending with zero food leads to starvation

### ISSUE THREAD

**Issue by sumpfralle** [FreeCol/freecol#30]
When a settlement ends up with 200 or more units of food, its population grows by one.

In case a settlement finishes with exactly 200 units of food, then one inhabitant of the settlement starves to death (even though the settlement produces a surplus of food) at the same turn. Thus the turn log contains two messages for the same settlement:
* population grows
* one citizen starved to death

This should not happen.

Version: nightly-2019-01-02

**Comment by mpope042** [comment]
I am unable to reproduce this error.  If it recurs, please open a [bug report](http://sourceforge.net/p/freecol/bugs) with an attached saved game that exhibits the problem.

**Comment by sumpfralle** [comment]
Thank you for taking the time to look into this issue.

I guess, it is fixed now. Next time I will attach the save game.

Thanks!
