### ISSUE TITLE
Goods are not partially loaded into a wagon or ship 

### ISSUE THREAD

**Issue by sumpfralle** [FreeCol/freecol#31]
I think, the UI once allowed the following situation:
* a wagon contains some units of food and 60 units of lumber
* dragging another 100 units of lumber into the wagon resulted automatically in the suitable partial load (loading only 40 units of lumber)

At the moment any load operation is discarded, if the number of items to be loaded exceeds the free storage. Loading with the shift key pressed down partially solves this issue, but it is not as convenient as automatic partial loading.

Version: nightly-2019-01-02

**Comment by mpope042** [comment]
IIRC the current behaviour is the result of someone complaining about it working the way you want it to.  IMHO the current behaviour is better because you get to choose.
