### ISSUE TITLE
Changing the task of a worker does not update all dependent statistics

### ISSUE THREAD

**Issue by sumpfralle** [FreeCol/freecol#33]
How to reproduce:
* the locally available lumber is not sufficient for the carpenter (e.g. the carpenter produces only 7 out of 14 units)
* assign an additional worker to the lumber task
* now the production statistics of the carpenter remain unchanged (still at 7/14 instead of 14/14)

The production summary at the top of the settlement is correct. Just the statistics of single buildings are not updated.

**Comment by mpope042** [comment]
I suspect this is BR#3168, fixed in git.73511db.
