### ISSUE TITLE
Settlement task list window does not open anymore after declaration of independence

### ISSUE THREAD

**Issue by sumpfralle** [FreeCol/freecol#35]
The list of things to be build in a settlement seems to be unavailable after declaring independency.

I did the following:
1. declare independence
2. opening the task list (in German "Bauwarteschlange") of a settlement fails silently: the window does not pop up
3. end the turn
4. try to open the task list again: it still fails silently
5. save and quit the game
6. start freecol again and continue the game
7. now the task list window can be opened (as expected)

I did not see any error messages on the terminal while running the game.

**Comment by mpope042** [comment]
I can not reproduce this problem, and suspect it may be something specific to the game you are playing.  Please consider submitting a detailed bug report on our main [bug tracker](https://sourceforge.net/p/freecol/bugs).  An attached saved game which exhibits the problem will almost certainly be necessary.
