### ISSUE TITLE
Flatpak submission to Flathub

### ISSUE THREAD

**Issue by rrigby** [FreeCol/freecol#38]
Hi, I've created a Flatpak manifest for FreeCol and I'm submitting it to Flathub.

If you are interested in helping maintain the flatpak manifest and having control over the repository feel free to join in this discussion. 

https://github.com/flathub/flathub/pull/932

**Comment by wintertime** [comment]
Sorry, this is only a small project, without the resources to help maintain packaging for linux distributions or package managers or similar.
Anyway, thank you for helping on making FreeCol more widely available.
