### ISSUE TITLE
Feature-Request: Right Click movement

### ISSUE THREAD

**Issue by warpspin** [FreeCol/freecol#67]
I know the original did not have it, but I would really love an option to move units by right-clicking on the tile where the currently selected unit should move to. Movement really fells cumbersome on a laptop without numpad.

**Comment by mpope042** [comment]
1. Middle mouse click
2. Right click on tile, top menu entry

The real FR here is to be able to remap the mouse clicks, which are currently hardwired.  [This](https://sourceforge.net/p/freecol/improvement-requests/) is a better place to make such a request.
