### ISSUE TITLE
Cannot continue after declare independence

### ISSUE THREAD

**Issue by atrejo** [FreeCol/freecol#71]
Hi, I have an issue in the save game that I attach, when I declare independence and finish the turn the system has the following log that I also attach, an error related to IA, the turn of the royal expeditionary force crashes the game and I cannot continue my path to the victory :(. I tried in many versions, from the ubuntu 0.11.6, the 0.11.3, snd finally in the latest nightly build freecol-git-20200914, I cleared all the config, cache and save folders, tried with java 14 amd 8, from oracle and openjdk, having the same crash under any situation, older versions doesn't even load my save file, but this is the second time I have this issue, in other I had the same issue with the turn of the expeditionary force.
To reproduce the issue load my save file, declare independence and end turn.
Thanks.

[Fastrus_Russian_1724_2_Autumn.zip](https://github.com/FreeCol/freecol/files/5308140/Fastrus_Russian_1724_2_Autumn.zip)
[log-issue.log](https://github.com/FreeCol/freecol/files/5308154/log-issue.log)

**Comment by mpope042** [comment]
This is reproducible, and probably related to a recently fixed problem.  Looking at it now.

**Comment by mpope042** [comment]
OK, there is a crash on declaration.  In the current trunk, for me at least, this is recoverable and the game continues.  However the fix was simple and with git.eb846f3d the crash no longer occurs.  That should do the trick, closing.

**Comment by atrejo** [comment]
again I cannot declare independence in this saved game:
[goldfff_Russian_1746_1_Spring.zip](https://github.com/FreeCol/freecol/files/6876954/goldfff_Russian_1746_1_Spring.zip)
