### ISSUE TITLE
Unresponsive on Ubuntu Desktop 18.04 LTS after showing dialogue box

### ISSUE THREAD

**Issue by paulvi** [FreeCol/freecol#77]
When trying to run the latest 0.11.6 version on Ubuntu Desktop 18.04 LTS,
the game seems slower comparing to when running on Windows (Though CPU usage is low, below 5%)

But critically when Yes/No dialogue is shown, the game becomes unresponsive (i.e. clicking anywhere has no effect)

```
$ uname -a
Linux ___ 5.0.0-32-generic #34~18.04.2-Ubuntu SMP Thu Oct 10 10:36:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
Intel CPU
nVidia card 1900x1280 HD resolution
16GB memory in the system

![image](https://user-images.githubusercontent.com/1614482/103562705-76623100-4ef6-11eb-9e4b-c81c83188066.png)

I was running from terminal from defaulr install folder `/home/user/freecol` as `./freecol`.
Ctrl+C from terminal does close the game instantly.

Switching to full screen mode does not matter. (I got the same issue after resuming the game)

**Comment by wintertime** [comment]
Have you tried using the latest Nightly Release? 0.11.6 is pretty old now and IIRC there have been fixes for that slowness meanwhile.

**Comment by paulvi** [comment]
I did try the latest available 20201224 build, and while I cannot run into exactly freezed/unresponsive situation, described in this issue, I have many other issues listed in #84 

Fully unresponsive is game stopper and is usually treated as high priority, however I don't have way to exactly reproduce fully unresponsive situation and it is just happens sometimes.
 
But I think the reason, the cause may be the same as for those smaller issues listed in #84

**Comment by paulvi** [comment]
I run again into the same issue with 0.11.6.

The game became unresponsive too clicks anywhere, I was checking CPU usage (it was 0), many alt-tab did not help.

However I found the reason for this issue: it happen when the first contact with a tribe happens directly by Scout  from ship to settlement. In this case game is present 2 dialogues:
- 1) "Meeting the Natives. Will you accept our treaty Yes|No"
- 2) What should Scout do.
The second dialogue is smaller, and as all dialogues are displayed in the center of screen, the second dialogue has appeared invisible under the fist one but somehow having the focus so clicks on the first Meeting the Natives dialogue or anywhere else had no response.

I did not took the screenshot right before and after when the second dialogue became visible, but this screenshot shows the usual situation just after.

![Screenshot from 2021-01-29 23-17-43](https://user-images.githubusercontent.com/1614482/106292902-59681600-6288-11eb-80e8-2568665e6270.png)

So 2 issues here:  
- some dialogues are not shown in Ubuntu desktop with 0.11.6.
- dialogues should not cover each other, especially when screen allows that.

**Comment by mpope042** [comment]
Dialog positioning has changed a lot since 0.11.6.  There is definitely code present that tries very hard to not put dialogs on top of each other, however this does not seem to work reliably on certain systems (including ubuntu + nvidia).

General unresponsiveness is often due to a crash, but once again, there have been intermittant reports of painfully slow graphics.  Unfortunately there is not enough information here to tell what is happening.  Please read [this](https://sourceforge.net/p/freecol/bugs/new/) if you want to help us to help you.

**Comment by mpope042** [comment]
Responsiveness is much improved in the new release 0.12.0.  Closing.
