### ISSUE TITLE
Sometimes AI assigns European units to worst producing tile 

### ISSUE THREAD

**Issue by bjorneg** [FreeCol/freecol#78]
Hi

It looks like the AI assigns European units to the least producing tile.
Look at the English tobe Colony at 33, 85 (I play Dutch - so use --debug MENUS)
At the next turn AI will assign one colonist to produce ore on the grain resource (34,86) and one unit producing grain at boreal forest (33, 83).

Save game file is attached:
[bug01_1494.zip](https://github.com/FreeCol/freecol/files/5860488/bug01_1494.zip)

I think the bug is caused by a wrongly sorted workplan in ColonyPlan.java. A patch is attached as well.
(https://github.com/FreeCol/freecol/files/5860502/Order-colony-resources-from-best-to-worst-in-workpla.zip)

I have played a couple of games with the patch applied and it works ok for me. I have not noted any side-effects with the patch applied.

I am at master 75e1cf3.

/////Björne

**Comment by Calebrw** [comment]
Can you create a pull request?

**Comment by bjorneg** [comment]
PR #79

**Comment by Calebrw** [comment]
Merged. Should make the game better.
