### ISSUE TITLE
Cannot unload cargo, cannot set back to new world

### ISSUE THREAD

**Issue by Beep6581** [FreeCol/freecol#8]
Commit 9ab8fb128

Sometimes my units cannot unload the goods, e.g. from a wagon train inside a colony, or from a ship inside a colony or back in the old world.

Probably a related bug is that sometimes I cannot set sail from the old world back to the new.

In both cases, saving the game, restarting Freecol and reloading the game unfudges it.

These bugs appear sporadically, perhaps once every 30 turns.

Saved games:
https://filebin.net/ua7m2j1ozn50aq0v

**Comment by Calebrw** [comment]
See https://sourceforge.net/p/freecol/bugs/3117/

**Comment by HighwayofLife** [comment]
This should be fixed in 7524bf1
