### ISSUE TITLE
No Horses for Seasoned Scout upon emigration

### ISSUE THREAD

**Issue by Calebrw** [FreeCol/freecol#81]
Full data: https://sourceforge.net/p/freecol/bugs/3220/

Coped for posterity.

**Comment by paulvi** [comment]
![](https://sourceforge.net/p/freecol/bugs/3220/attachment/Screenshot%202021-01-26%20193232.png)

**Comment by paulvi** [comment]
I wonder from game play if it really possible a) for Seasoned Scout to appear in Europe b) appear without horses

If b) is positive, than it is maybe just UI bug, that displays Seasoned Scout as mounted without proper check that the unit has no actually horses.

Similar possibility is for Veteran soldier, while it is usual to appear in docks unmounted, maybe it can also be without musettes.
And similar, what would Turn Report will show?

**Comment by mpope042** [comment]
I think it is possible for a scout to appear without horses.  It is unclear which part of the display is incorrect.  We would need the save game to determine for certain whether the horses were there or not.

In general, please report bugs like this [here](http://sourceforge.net/p/freecol/bugs), this issue tracker is not checked regularly.

**Comment by Calebrw** [comment]
> In general, please report bugs like this [here](http://sourceforge.net/p/freecol/bugs), this issue tracker is not checked regularly.

Mike,

I did report: https://sourceforge.net/p/freecol/bugs/3220/ at the time.

**Comment by mpope042** [comment]
Sorry Caleb, I am trying to catch up quickly here.  That explains why the bug sounded familiar!:-)  Will close this report as the SF one is better.
