### ISSUE TITLE
Illegal attack move - privateer vs caravel

### ISSUE THREAD

**Issue by Beep6581** [FreeCol/freecol#9]
https://filebin.net/qdf25sqwlszierzt
74e2fd2cf

**Comment by HighwayofLife** [comment]
Please open a ticket in the [SourceForge Bug tracker](https://sourceforge.net/p/freecol/bugs/?source=navbar) with more information. Please provide scenario and a save game, along with a log file attached. Thanks!

**Comment by Beep6581** [comment]
SourceForge is a dirty company and their platform is outdated, I don't want to use it.

I did provide a saved game and a log but they were ignored.

**Comment by Beep6581** [comment]
Closing as the filebin has expired.
