### ISSUE TITLE
Font displays very bad

### ISSUE THREAD

**Issue by unsermanninchina** [FreeCol/freecol#95]
I am running FreeCol on a Laptop on an up to date Manjaro linux with an 5.11.16-2-MANJARO kernel, KDE 5.21.4 and X11. 
`java -version
openjdk version "15.0.2" 2021-01-19
OpenJDK Runtime Environment (build 15.0.2+7)
OpenJDK 64-Bit Server VM (build 15.0.2+7, mixed mode)
`
Since a while I have a problem with the fonts. I am sure, that has nothing to to with freecol, but with my Java installation. However, I didn't find an answer online until now. Maybe somebody here has an idea what the problem is?

Thank you very much in advance and thank you as well for your efforts to make this great game, which I play since many years!
![Screenshot_Freecol](https://user-images.githubusercontent.com/324880/116832239-92e15200-abe6-11eb-9140-566597a60336.png)

**Comment by wintertime** [comment]
Yes, I think, something with your Java installation or the Fonts on your system is broken. The game mostly uses fonts provided by Java (except the Gothic font in the dialog title the game provides).
I'd suggest trying to reinstall Java or Font packages.

**Comment by unsermanninchina** [comment]
@wintertime thank you. I reinstalled Java and it workes again like before. Cheers!
