### ISSUE TITLE
Cannot continue after declare independence

### ISSUE THREAD

**Issue by atrejo** [FreeCol/freecol#98]
Hi, I cannot go forward after declare independence in the following saved game:

I know for other saves I put on the previous report for this issue it was solved, but now it's again with this save file:

[goldfff_Russian_1746_1_Spring.zip](https://github.com/FreeCol/freecol/files/6876979/goldfff_Russian_1746_1_Spring.zip)

**Comment by atrejo** [comment]
I leave the log for information

	INFO: Unitbuttons at 1876,2066 spaced 5 in 3768,2071
	Mon Jul 26 19:30:23 CDT 2021
	Thread: 19
net.sf.freecol.client.gui.panel.InfoPanel update
	INFO: InfoPanel maintained UNIT -> UNIT with unit [unit:8295 russian colonialRegular-dragoon 2(1/3) /4]
	Mon Jul 26 19:30:23 CDT 2021
	Thread: 19
net.sf.freecol.client.gui.panel.CornerMapControls getComponentsToAdd
	INFO: Unitbuttons at 1876,2066 spaced 5 in 3768,2071
	Mon Jul 26 19:30:34 CDT 2021
	Thread: 19
net.sf.freecol.client.gui.panel.InfoPanel update
	INFO: InfoPanel maintained UNIT -> UNIT with unit [unit:8295 russian colonialRegular-dragoon 2(1/3) /4]
	Mon Jul 26 19:30:34 CDT 2021
	Thread: 19
net.sf.freecol.client.gui.panel.InfoPanel update
	INFO: InfoPanel maintained UNIT -> UNIT with unit [unit:8295 russian colonialRegular-dragoon 2(1/3) /4]
	Mon Jul 26 19:30:34 CDT 2021
	Thread: 19
net.sf.freecol.client.gui.panel.CornerMapControls getComponentsToAdd
	INFO: Unitbuttons at 1876,2066 spaced 5 in 3768,2071
	Mon Jul 26 19:30:34 CDT 2021
	Thread: 19
net.sf.freecol.client.gui.panel.InfoPanel update
	INFO: InfoPanel maintained UNIT -> UNIT with unit [unit:8295 russian colonialRegular-dragoon 2(1/3) /4]
	Mon Jul 26 19:30:34 CDT 2021
	Thread: 19
net.sf.freecol.client.gui.panel.CornerMapControls getComponentsToAdd
	INFO: Unitbuttons at 1876,2066 spaced 5 in 3768,2071
	Mon Jul 26 19:30:38 CDT 2021
	Thread: 19
net.sf.freecol.client.gui.panel.InfoPanel update
	INFO: InfoPanel maintained UNIT -> UNIT with unit [unit:8295 russian colonialRegular-dragoon 2(1/3) /4]
	Mon Jul 26 19:30:38 CDT 2021
	Thread: 19
net.sf.freecol.server.ai.REFAIPlayer initialize
	WARNING: REF found no targets.
	Mon Jul 26 19:30:38 CDT 2021
	Thread: 1436
net.sf.freecol.server.control.InGameController endTurn
	SEVERE: REF failed to initialize.
	Mon Jul 26 19:30:38 CDT 2021
	Thread: 1436
net.sf.freecol.server.model.ServerPlayer csChangeStance
	INFO: Stance modification Catherine I UNCONTACTED -> PEACE wrt Segoyewatha
	Mon Jul 26 19:30:38 CDT 2021
	Thread: 1437
net.sf.freecol.server.model.ServerPlayer csChangeStance
	INFO: Stance modification Segoyewatha UNCONTACTED -> PEACE wrt Catherine I (symmetric)
	Mon Jul 26 19:30:38 CDT 2021
	Thread: 1437
net.sf.freecol.server.model.ServerPlayer csChangeStance
	INFO: Stance modification Catherine I UNCONTACTED -> PEACE wrt Guaira
	Mon Jul 26 19:30:38 CDT 2021
	Thread: 1437
net.sf.freecol.server.model.ServerPlayer csChangeStance
	INFO: Stance modification Guaira UNCONTACTED -> PEACE wrt Catherine I (symmetric)
	Mon Jul 26 19:30:38 CDT 2021
	Thread: 1437
net.sf.freecol.server.model.ServerPlayer csChangeStance
	INFO: Stance modification Catherine I UNCONTACTED -> PEACE wrt Tamanaco
	Mon Jul 26 19:30:38 CDT 2021
	Thread: 1437
net.sf.freecol.server.model.ServerPlayer csChangeStance
	INFO: Stance modification Tamanaco UNCONTACTED -> PEACE wrt Catherine I (symmetric)
	Mon Jul 26 19:30:38 CDT 2021
	Thread: 1437
net.sf.freecol.server.model.ServerPlayer csChangeStance
	INFO: Stance modification Catherine I UNCONTACTED -> PEACE wrt Geronimo
	Mon Jul 26 19:30:38 CDT 2021
	Thread: 1437
net.sf.freecol.server.model.ServerPlayer csChangeStance
	INFO: Stance modification Geronimo UNCONTACTED -> PEACE wrt Catherine I (symmetric)
	Mon Jul 26 19:30:38 CDT 2021
	Thread: 1437
net.sf.freecol.server.model.ServerPlayer csChangeStance
	INFO: Stance modification Catherine I UNCONTACTED -> PEACE wrt Atahualpa
	Mon Jul 26 19:30:38 CDT 2021
	Thread: 1437
net.sf.freecol.server.model.ServerPlayer csChangeStance
	INFO: Stance modification Atahualpa UNCONTACTED -> PEACE wrt Catherine I (symmetric)
	Mon Jul 26 19:30:38 CDT 2021
	Thread: 1437
net.sf.freecol.server.model.ServerPlayer csChangeStance
	INFO: Stance modification Catherine I UNCONTACTED -> PEACE wrt Moctezuma II
	Mon Jul 26 19:30:38 CDT 2021
	Thread: 1437
net.sf.freecol.server.model.ServerPlayer csChangeStance
	INFO: Stance modification Moctezuma II UNCONTACTED -> PEACE wrt Catherine I (symmetric)
	Mon Jul 26 19:30:38 CDT 2021
	Thread: 1437
net.sf.freecol.server.model.ServerPlayer csChangeStance
	INFO: Stance modification Catherine I UNCONTACTED -> PEACE wrt Louis XIV
	Mon Jul 26 19:30:38 CDT 2021
	Thread: 1437
net.sf.freecol.server.model.ServerPlayer csChangeStance
	INFO: Stance modification Louis XIV UNCONTACTED -> PEACE wrt Catherine I (symmetric)
	Mon Jul 26 19:30:38 CDT 2021
	Thread: 1437
net.sf.freecol.server.model.ServerPlayer csChangeStance
	INFO: Stance modification Catherine I UNCONTACTED -> PEACE wrt Elizabeth I
	Mon Jul 26 19:30:38 CDT 2021
	Thread: 1437
net.sf.freecol.server.model.ServerPlayer csChangeStance
	INFO: Stance modification Elizabeth I UNCONTACTED -> PEACE wrt Catherine I (symmetric)
	Mon Jul 26 19:30:38 CDT 2021
	Thread: 1437
net.sf.freecol.server.model.ServerPlayer csChangeStance
	INFO: Stance modification Catherine I UNCONTACTED -> PEACE wrt Philip II
	Mon Jul 26 19:30:38 CDT 2021
	Thread: 1437
net.sf.freecol.server.model.ServerPlayer csChangeStance
	INFO: Stance modification Philip II UNCONTACTED -> PEACE wrt Catherine I (symmetric)
	Mon Jul 26 19:30:38 CDT 2021
	Thread: 1437
java.util.logging.LogManager$RootLogger log
	WARNING: Uncaught exception from thread: Thread[FreeColServer:AIPlayer(Catherine I),6,main]
	Mon Jul 26 19:30:44 CDT 2021
	Thread: 1437
	Stack trace:
java.lang.NullPointerException
	at net.sf.freecol.common.model.Unit.realStart(Unit.java:3001)
	at net.sf.freecol.common.model.Unit.findPath(Unit.java:2940)
	at net.sf.freecol.common.model.Unit.findPath(Unit.java:2916)
	at net.sf.freecol.common.model.Unit.shouldTakeTransportTo(Unit.java:2821)
	at net.sf.freecol.server.ai.mission.UnitSeekAndDestroyMission.getTransportDestination(UnitSeekAndDestroyMission.java:388)
	at net.sf.freecol.server.ai.AIUnit.getTransportDestination(AIUnit.java:597)
	at net.sf.freecol.server.ai.mission.Mission.invalidTransportableReason(Mission.java:310)
	at net.sf.freecol.server.ai.AIUnit.invalidReason(AIUnit.java:786)
	at net.sf.freecol.server.ai.mission.TransportMission.invalidCargoReason(TransportMission.java:1216)
	at net.sf.freecol.server.ai.mission.TransportMission.invalidReason(TransportMission.java:1392)
	at net.sf.freecol.server.ai.mission.Mission.isValid(Mission.java:187)
	at net.sf.freecol.server.ai.REFAIPlayer.giveNormalMissions(REFAIPlayer.java:613)
	at net.sf.freecol.server.ai.EuropeanAIPlayer.startWorking(EuropeanAIPlayer.java:2261)
	at net.sf.freecol.server.ai.REFAIPlayer.startWorking(REFAIPlayer.java:898)
	at net.sf.freecol.server.ai.AIPlayer.lambda$setCurrentPlayerHandler$12(AIPlayer.java:516)
	at java.lang.Thread.run(Thread.java:748)
----------------------------

**Comment by Calebrw** [comment]
This issue was fixed. See [BR3246](https://sourceforge.net/p/freecol/bugs/3246/) on SourceForge.
